import os

# Path to the root of the project
PATH_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
# Path to the data directory
PATH_DATA = os.path.join(PATH_ROOT, 'data')
PATH_DATA_RAW = os.path.join(PATH_DATA, 'raw')

TEAM_KNOWN = ['Gonzaga', 'Kansas', 'Duke', 'Arizona', 'Villanova', 'Virginia', 'North Carolina', 'Kentucky',
              'Michigan St.', 'Oregon', "Saint Mary's", 'Wichita St.', 'Houston', 'San Diego St.', 'VCU', 'Michigan',
              'Wisconsin', 'Cincinnati', 'Purdue', 'Belmont', 'UCLA', 'Baylor', 'Vermont', 'New Mexico St.', 'Xavier',
              'Arkansas', 'Creighton', 'BYU', 'Louisiana Tech', 'Miami FL', 'Stephen F. Austin', 'Florida',
              'South Dakota St.', 'Ohio St.', 'Tennessee', 'Memphis', 'Toledo', 'Maryland', 'Dayton', 'Murray St.',
              'Iona', 'Louisville', 'Connecticut', 'UC Irvine', 'UAB', 'Akron', 'Iowa', 'Syracuse', 'Middle Tennessee',
              'Providence', 'Davidson', 'Boise St.', 'West Virginia', 'Notre Dame', 'Kent St.', 'Indiana', 'Iowa St.',
              'Texas', 'Colorado', 'Alabama', 'Marquette', 'Sam Houston St.', 'SMU', 'Buffalo', 'Kansas St.',
              'Texas A&M', 'Florida St.', 'College of Charleston', 'Louisiana Lafayette', 'Oklahoma', 'Wright St.',
              'USC', 'Texas Tech', 'Weber St.', 'Nevada', 'Utah St.', 'Montana', 'Old Dominion', 'Florida Gulf Coast',
              'North Dakota St.', 'North Carolina St.', 'LSU', 'Western Kentucky', 'St. Bonaventure', 'Winthrop',
              'Ohio', 'Seton Hall', 'Loyola Chicago', 'Clemson', 'Texas Southern', 'Illinois', 'Georgia St.', 'Wofford',
              'Norfolk St.', 'Colorado St.', 'Saint Louis', 'Butler', 'Auburn', 'Stony Brook', 'Utah', 'Mississippi',
              'Valparaiso', 'Arizona St.', 'UC Santa Barbara', 'Grand Canyon', 'Oklahoma St.', 'Hofstra', 'New Mexico',
              'East Tennessee St.', 'Virginia Tech', 'Northern Iowa', 'North Carolina Central', 'Liberty', 'Hawaii',
              'Chattanooga', 'UNC Greensboro', 'Eastern Washington', 'San Francisco', 'Furman', 'Bucknell', 'Richmond',
              'Fresno St.', 'UNLV', 'Temple', 'Albany', 'Stanford', 'Eastern Kentucky', 'Mercer', 'TCU', 'Pittsburgh',
              'UT Arlington', 'Princeton', 'Morehead St.', 'Utah Valley', 'North Texas', 'Radford', 'Mississippi St.',
              'Yale', 'Wyoming', 'Towson', 'Wagner', 'Drake', 'Oakland', 'Minnesota', 'Illinois St.', 'Lipscomb',
              "St. John's", 'UCF', 'Colgate', 'Marshall', 'Northern Kentucky', 'Washington', 'Rhode Island',
              'George Washington', 'Texas A&M Corpus Chris', 'Southern Illinois', 'Coastal Carolina', 'UNC Wilmington',
              'Gardner Webb', 'Penn St.', 'Boston University', 'South Carolina', 'Northeastern', 'UNC Asheville',
              'Missouri', 'Northwestern', 'Georgia', 'Vanderbilt', 'Rider', 'Monmouth', 'Harvard', 'Tulsa', 'UTEP',
              'Jacksonville St.', 'Santa Clara', 'Georgia Southern', 'Oral Roberts', 'Missouri St.', 'Georgia Tech',
              'Texas St.', "Saint Joseph's", 'James Madison', 'Canisius', 'Indiana St.', 'Georgetown', 'Lehigh',
              'Massachusetts', 'Seattle', 'George Mason', 'Robert Morris', 'Northern Colorado', 'Southern Miss',
              'Delaware', 'Montana St.', 'UC Davis', 'Long Beach St.', "Saint Peter's", 'South Dakota',
              "Mount St. Mary's", 'Green Bay', 'Bradley', 'High Point', 'Nebraska', 'South Alabama', 'Hampton', 'Navy',
              'Southern', 'Bowling Green', 'Siena', 'Wake Forest', 'Cleveland St.', 'California', 'Ball St.', 'Army',
              'Evansville', 'Cal St. Bakersfield', 'UMBC', 'North Florida', 'Campbell', 'William & Mary', 'Charlotte',
              'Florida Atlantic', 'Nicholls St.', 'Eastern Michigan', 'Arkansas St.', 'Manhattan', 'Quinnipiac',
              'Southeastern Louisiana', 'LIU Brooklyn', 'Troy', 'Cal St. Fullerton', 'Rutgers', 'Samford', 'Bryant',
              'La Salle', 'Central Michigan', 'Youngstown St.', 'San Diego', 'FIU', 'Abilene Christian',
              'Western Michigan', 'Milwaukee', 'Oregon St.', 'Hartford', 'Elon', 'Loyola Marymount', 'St. Francis NY',
              'Fairfield', 'Washington St.', 'Denver', 'Portland St.', 'Prairie View A&M', 'Tulane', 'East Carolina',
              'Jacksonville', 'NJIT', 'Tennessee Martin', 'Southeast Missouri St.', 'Duquesne', 'Holy Cross',
              'Jackson St.', 'Southern Utah', 'Appalachian St.', 'Louisiana Monroe', 'Miami OH', 'Austin Peay',
              'Drexel', 'Northwestern St.', 'Morgan St.', 'Sacramento St.', 'USC Upstate', 'Tennessee Tech',
              'St. Francis PA', 'New Hampshire', 'Pacific', 'North Dakota', 'Detroit', 'New Orleans',
              'Western Carolina', 'Rice', 'Idaho', 'North Carolina A&T', 'Niagara', 'Penn', 'Loyola MD', 'UMass Lowell',
              'Illinois Chicago', 'American', 'Fairleigh Dickinson', 'UTSA', 'Boston College', 'Nebraska Omaha',
              'Air Force', 'Tennessee St.', 'Fordham', 'UMKC', 'Northern Illinois', 'Portland', 'Pepperdine',
              'Alcorn St.', 'Brown', 'UC Riverside', 'Sacred Heart', 'Longwood', 'DePaul', 'South Florida', 'Lafayette',
              'Howard', 'Charleston Southern', 'Eastern Illinois', 'UT Rio Grande Valley', 'Western Illinois', 'VMI',
              'Grambling St.', 'Columbia', 'Alabama St.', 'Stetson', 'Lamar', 'Fort Wayne', 'Arkansas Pine Bluff',
              'Bethune Cookman', 'Northern Arizona', 'Cornell', 'Marist', 'McNeese St.', 'Kennesaw St.',
              'SIU Edwardsville', 'The Citadel', 'Idaho St.', 'Cal St. Northridge', 'Cal Poly', 'Central Arkansas',
              'Maryland Eastern Shore', 'Incarnate Word', 'Savannah St.', 'South Carolina St.', 'Central Connecticut',
              'IUPUI', 'Dartmouth', 'Binghamton', 'Presbyterian', 'Alabama A&M', 'Florida A&M', 'Coppin St.',
              'Houston Baptist', 'San Jose St.', 'Delaware St.', 'IPFW', 'Arkansas Little Rock', 'Maine', 'Cal Baptist',
              'Little Rock', 'Chicago St.', 'Mississippi Valley St.', 'North Alabama', 'Bellarmine', 'Merrimack',
              'Tarleton St.', 'UC San Diego', 'St. Thomas', 'Utah Tech', 'Houston Christian', 'Queens',
              'Southern Indiana', 'Stonehill', 'Texas A&M Commerce', 'Lindenwood', 'Dixie St.']
